#
###################################
# Site wide configuration
####################################
#
title: Magic garage
email: maciek.anuszkiewicz@gmail.com
description: The place between software and hardware
url: https://exmagic.github.io # the base hostname & protocol for your site
keywords: ["Programming"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          Europe/Oslo
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title


kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Maciek

  email: maciek.anuszkiewicz@gmail.com
  disqus-shortname: magic-garage
  twitter: MAnuszkiewicz #username
  facebook: #username
  google:
    plus: #username
    analytics: UA-114923830-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: exMagic #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: renyuan-zou-69b7038a  #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
  telegram: #username
